### PR TITLE
Update and add new profiles extensions

### PR DESCRIPTION
**Pull request by andrew-gardener**
- Fix existing tests 
- Update Resource Management actions 
    - Add `Downloaded`, `Printed`, `Saved`, and `Uploaded` based on IMSGlobal/caliper-central#206
- Add Tool Use profile extension 
    - adds Collection, AggregateMeasure, and AggregateMeasureCollection entities
    - extends ToolUseEvent to handle AggregateMeasureCollection in generated (set context to Tool Use profile extension)
- Add feedback profile 
- Add Survey Profile

### CODE REVIEW

**Comment by lsloan** [comment]
Hi, @andrew-gardener.  I'll review your PR soon, probably tomorrow.

**Comment by lsloan** [comment]
@andrew-gardener, what do you think of using PHP function argument type declarations?  (https://www.php.net/manual/en/functions.arguments.php#functions.arguments.type-declaration.types)

Some of the code already uses it (https://github.com/IMSGlobal/caliper-php/pull/336/files#diff-8c37cd48d5c23a1b6eebc9217dda171fR64) and it allows passing a null.  Should we extend that to arguments of basic types, like string?

**Comment by andrew-gardener** [comment]
@lsloan sounds good to me. 
We'd need to up the minimum version of php though (currently minimum is 5.4~5.6 from the README) which is probably a good idea anyways.

**Comment by lsloan** [comment]
Maybe we should set function argument typing as a goal of a future PR rather than try to shoehorn it into this one.  That's a PHP-specific issue rather than this PR, which resolves Caliper specification issues.

**Comment by andrew-gardener** [comment]
Sounds like a good refactor plan.

**Comment by lsloan** [comment]
Merged! :shipit: 

Are you working on any other issues for Caliper 1.2?  What else is outstanding that I can work on?

**Comment by andrew-gardener** [comment]
@lsloan I haven't been touching anything strictly 1.2 related (was mostly trying to get profiles done which I needed for some of the tools I'm caliperizing). I think there is only 1.2 things left to do for caliper-php from the spreadsheet of doom (https://docs.google.com/spreadsheets/d/12AmcHzmsbX28Cw0RfN8e2hoNYPIgNcOEpCZ-t3YZwdg/edit#gid=1463230260) but I'm not sure how up to date it is anymore (just updated with the caliper-php profile additions)

**Pull request merged**
