### PR TITLE
Add GitHub actions

### LINKED ISSUE #344: Use Travis-CI for builds
Just adding in project issues for the last few remaining tasks for a v1.2 release

### PR DESCRIPTION
**Pull request by andrew-gardener**
Also update phpunit and fix tests for php 8 

Closes #344

### CODE REVIEW

**Comment by andrew-gardener** [comment]
You can see an example run here: https://github.com/andrew-gardener/caliper-php/runs/1930424258?check_suite_focus=true (manually change it to run on all branches. the way its setup currently is that it will run on all tags, master, develop and PRs to master+develop)

**Comment by bracken** [comment]
Merging this into develop to see if it runs.

**Comment by andrew-gardener** [comment]
looks like the deps install failed in the php 7.3 for some reason. might need to re-run

**Comment by bracken** [comment]
It ran! It failed too, but that's fine. Is there a way to make it run the build on PR's?

**Comment by andrew-gardener** [comment]
It should run the build on PRs in the future on its in develop (I believe that it works like travis that it will only do PR runs if the job code is in the branch you're trying to PR into)

**Comment by bracken** [comment]
\o/ passed on the re-run! thanks andrew, this is awesome!

**Comment by andrew-gardener** [comment]
I'll rebase the other PR so we can see if it runs tests correctly on a PR

**Comment by bracken** [comment]
Great idea

**Pull request merged**
